### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by eightsixeight** [sipwise/rate-o-mat#1]
Anyway to have a debug file of the current cdr rating ? 

it seems its not charging altough my only billing profile/fee/zone has fees.

**Comment by eightsixeight** [comment]
actually figure debug=1 in tt2 file reapply..

found that rates fails with 

Dec  5 13:07:33  (info) rate-o-mat[1676]: DEBUG: calculating call cost for profile_id 1 with type call, direction out, src_user_domain 14185551234@sip.mydomain.com, dst_user_domain 14184441111@192.76.1.2
Dec  5 13:07:33 (info) rate-o-mat[1676]: DEBUG: rating cdr ID 18 aborted after 1.412 secs
Dec  5 13:07:33 (info) rate-o-mat[1676]: INFO: Caught DBI:err 1690

**Comment by eightsixeight** [comment]
could be to do with cdr's not processed and profile or billing deleted or customer or something.. still debugging this one.. for now i removed from cdr where id < my last call

**Comment by eightsixeight** [comment]
Again.. same problem..
DBD::mysql::st execute failed: BIGINT UNSIGNED value is out of range in '(_i@8 - 1)' at /usr/sbin/rate-o-mat line 1528.

**Comment by eightsixeight** [comment]
finding the reason i show that yout rating is passing a null match to the function..

billing.get_billing_fee_id('1','call','in','15551234@192.1.2.3','14181231234@sip.domain.com',null);


FUNCTION `get_billing_fee_id`(
  _billing_profile_id int(11),
  _type enum('call','sms'),
  _direction enum('in','out'),
  _source varchar(511),
  _destination varchar(511),
  _match_mode enum('regex_longest_pattern', 'regex_longest_match', 'prefix', 'exact_destination')
) RETURNS int(11)
    READS SQL DATA
    DETERMINISTIC
begin

**Comment by eightsixeight** [comment]
or not.. hmm 

MariaDB [billing]> select * FROM billing.billing_fees_history WHERE id = billing.get_billing_fee_id('1','call','in','15551234','14','prefix');

ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(_i@8 - 1)'

**Comment by rkrenn** [comment]
also reported in the spce-user list.
fixed here https://github.com/sipwise/db-schema/commit/b74b1748f49d87a9906789abf41f761844a06dc8 for upcoming 6.5.x, 7.1.x and 7.2.
